# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ce9cc07f6d3b75b4ab2e3d8c0988ecf"
name = "JadePuma-Functions"
handle = "jade-puma-functions"
application_url = "https://ongoing-previews-ti-album.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jadepuma-functions-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_payment_customizations"

[auth]
redirect_urls = [
  "https://ongoing-previews-ti-album.trycloudflare.com/auth/callback",
  "https://ongoing-previews-ti-album.trycloudflare.com/auth/shopify/callback",
  "https://ongoing-previews-ti-album.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
